version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    environment:
      - DISCORD_TOKEN
  clickhouse:
    image: clickhouse:24.12
    volumes:
      - type: bind
        source: ./ch_data
        target: /var/lib/clickhouse
        bind:
          create_host_path: true
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  node_modules: