version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    command: yarn run dev
    environment:
      - DISCORD_TOKEN

volumes:
  node_modules: